pipeline {
    agent any
    environment {
        tag = "smart-displays"
        registry = "http://192.168.2.70:5000"
        dockerImage = ""
    }
    stages {

        stage('Clone') {
            steps {
                checkout scm
            }
        }

        stage('Build image') {
            steps {
                script {
                    dockerImage = docker.build(tag + ":${env.BUILD_ID}", "-f src/smart-display/Dockerfile .")
                }
            }
        }

        stage('Push image') {
            steps {
                script {
                    docker.withRegistry(registry) {
                        dockerImage.push("${env.BRANCH_NAME}")
                    }

                    def CURRENT_TAG = sh(returnStdout: true, script: "git tag -l --points-at HEAD | tail -1").trim()
                    if (CURRENT_TAG != "") {
                        docker.withRegistry(registry, registryCredential) {
                            dockerImage.push("${CURRENT_TAG}")
                        }
                    }
                }
            }
        }
    }
}